spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgresql
    url: jdbc:postgresql://10.140.0.3:5432/postgresql
    username: postgresql
    password: postgrespassword
  rabbitmq:
    host: 10.146.0.2
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.146.0.3,10.146.0.5,10.146.0.6,10.146.0.7
      port: 9200